version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: smart-librarian-api:latest
    env_file: .env
    environment:
      - PERSIST_DIR=/app/chroma_store
    volumes:
      - ./chroma_store:/app/chroma_store
      - ./:/app
    ports:
      - "8000:8000"
